<a href="https://colab.research.google.com/github/Waseem-Gopang/Data-Science/blob/main/Lab_10_20SW022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Lab # 10 Tasks***

Implement two of the classifiers (Decision tree and na√Øve bayes) and compare the performance of each classifier.

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/PS_20174392719_1491204439457_log.csv')

The below column reference:

step: represents a unit of time where 1 step equals 1 hour
type: type of online transaction
amount: the amount of the transaction
nameOrig: customer starting the transaction
oldbalanceOrg: balance before the transaction
newbalanceOrig: balance after the transaction
nameDest: recipient of the transaction
oldbalanceDest: initial balance of recipient before the transaction
newbalanceDest: the new balance of recipient after the transaction
isFraud: fraud transaction

In [ ]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [ ]:
df.isnull().sum()

step              0
type              0
amount            1
nameOrig          1
oldbalanceOrg     1
newbalanceOrig    1
nameDest          1
oldbalanceDest    1
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [ ]:

df.dropna( inplace=True)
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
395813,18,CASH_OUT,159460.65,C764863652,31216.00,0.00,C1874138331,16962.30,176422.96,0.0,0.0
395814,18,PAYMENT,5310.17,C1759198927,203596.00,198285.83,M1158151986,0.00,0.00,0.0,0.0
395815,18,CASH_OUT,200024.34,C2138093782,60236.00,0.00,C454268308,87708.32,287732.66,0.0,0.0
395816,18,PAYMENT,12610.12,C1700380760,99249.61,86639.49,M1413855098,0.00,0.00,0.0,0.0
395817,18,CASH_OUT,407474.21,C784415919,86639.49,0.00,C2013101993,1027316.09,1434790.30,0.0,0.0

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [ ]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

# Assuming you have a DataFrame named 'df' with your dataset

# Define features (X) and target variable (y)
X =df[['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest','type']]

X = pd.get_dummies(data=X, columns=['type'], drop_first=True)

# Define target variable
y = df['isFraud']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(df.shape)
print(X_train.shape[0])
print(X_test.shape[0])

(395818, 11)
277072
118746

NAIVE BAYES

In [ ]:

naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)

predictions = naive_bayes.predict(X_test)

In [ ]:

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
Accuracy_score2=accuracy_score(y_test,predictions)
Precision_score2=precision_score(y_test,predictions)
Recall_score2=recall_score(y_test,predictions)
F1_score2=f1_score(y_test,predictions)

Decision Tree

In [ ]:

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predict with Decision Tree Classifier
tree_predictions = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
Accuracy_score1=accuracy_score(y_test, tree_predictions)
Precision_score1=precision_score(y_test, tree_predictions)
Recall_score1=recall_score(y_test, tree_predictions)
F1_score1=f1_score(y_test, tree_predictions)

In [ ]:
# Making predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate the accuracy
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
print('The training accuracy is', train_accuracy)
print('The test accuracy is', test_accuracy)

The training accuracy is 1.0
The test accuracy is 0.9995705118488202

Comparision

In [ ]:
import pandas as pd

data = {
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score'],
    'Decision Tree': [Accuracy_score1, Precision_score1, Recall_score1, F1_score1],
    'na√Øve bayes': [Accuracy_score2, Precision_score2, Recall_score2, F1_score2]
}

df = pd.DataFrame(data)
print(df)

      Metric  Decision Tree  na√Øve bayes
0   Accuracy       0.999571     0.984252
1  Precision       0.456140     0.006494
2     Recall       0.565217     0.260870
3   F1-Score       0.504854     0.012672

In [ ]:
from scipy.stats import ttest_rel

# Assuming you have arrays of evaluation scores for both classifiers (e.g., accuracy_scores1, accuracy_scores2)
t_stat, p_value = ttest_rel(Accuracy_score1,Accuracy_score2)

if p_value < 0.05:
    print("There is a significant difference in performance.")
else:
    print("There is no significant difference in performance.");

There is no significant difference in performance.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1103: RuntimeWarning: divide by zero encountered in divide
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1103: RuntimeWarning: invalid value encountered in double_scalars
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero